@startuml
actor User
boundary "UI" as UI
control "PostService" as C
participant "UserRepository" as UR <<repository>>
participant "PostRepository" as PTR <<repository>>
participant "ImageRepository" as IR <<repository>>
entity "actual:Sesion" as S
entity "New:Post" as P

User -> UI : optionCreatePost()
UI -> UI: showNewPost()
User -> UI: takeTitle()
User -> UI: takeContent()
UI -> UI: regexValidateFields()
User -> UI: takeImage()
UI -> UI: covertImageToBase64()
UI -> UI: getSesion()
UI -> S: getSesion()
UI -> C: createPost()
C -> UR: authUser() 
create P
C --> P : new()
C -> C: isPageOrProfile()
C -> P: setPage()
C -> P: setAuthor()
C -> C: hasImage()
C -> IR: upload() 
C -> P: setImage()
C -> P: setTitle()
C -> P: setContent()
C -> P: setStatus()
C -> P: setViews()
C -> P: setUpVoters()
C -> P: setDownVoters()
C -> C : getPostDate()
C -> P: setCreatedAt()
C -> P: setUpdatedAt()
C -> PTR: save()
C -> C: createPostResponse()
C -> UI: createPostResponse()
UI -> UI: displaySuscess()
UI -> UI: navigatePostDetail()
C -> C : endUS()

hide footbox
@enduml
