@startuml entity-model
left to right direction
skinparam nodesep 50
skinparam ranksep 50

    enum Role {
        USER
        MODERATOR
        ADMIN
    }

    enum Status {
        ACTIVE
        INACTIVE
        DELETED
        BANNED
    }

    class Category {
        - String id
        - String name
    }

    class PageType {
        - String id
        - String name
    }

    class Instrument {
        - String id
        - String name
    }

    class Style {
        - String id
        - String name
    }

    class Comment {
        - String id
        - User author
        - Post post
        - Comment? replyTo
        - String content
        - List<User> upvoters
        - List<User> downvoters
        - LocalDateTime createdAt
        - LocalDateTime updatedAt
        - PageProfile pageProfile
        - Status status
    }

    class Post {
        - String id
        - String title
        - String content
        - Integer views
        - String authorId
        - Page? page
        - String? imageId
        - List<UserProfile> upvoters
        - List<UserProfile> downvoters
        - Category category
        - LocalDateTime createdAt
        - LocalDateTime updatedAt
        - Status status
    }

    class User {
        - String id
        - String email
        - String password
        - Status status
        - List<Role> roles
    }

    class UserProfile {
        - String id
        - String email
        - String name
        - String surname
        - LocalDateTime memberSince
        - String portraitImage
        - String profileImage
        - String shortDescription
        - String longDescription
        - Boolean isFollowing
        - List<String> following
        - List<Style> styles
        - List<Instrument> instruments
    }

    class PageProfile {
        - String id
        - String name
        - String portraitImage
        - String profileImage
        - String shortDescription
        - String longDescription
        - String ownerId
        - Status status
        - PageType pageType
        - Boolean isFollowing
        - List<UserProfile> members
    }

    class Event {
        - String id
        - String title
        - String content
        - Integer views
        - String authorId
        - Page? page
        - String? imageId
        - LocalDateTime dateInit
        - LocalDateTime dateEnd
        - LocalDateTime createdAt
        - LocalDateTime updatedAt
        - Status status
        - List<String> assists

        + calculateAssistsQuantity()
        + setIsAssisting()
      
    }

     enum EventStatus {
        UPCOMING
        IN_PROGRESS
        ENDED
        CANCELED
        DELETED
    }

    class Review {
        - String id
        - String reviewedId
        - UserProfile reviewerUser
        - String review
        - Float rating
        - LocalDateTime createdAt
        - LocalDateTime updatedAt
        - Status status  
    }

    class Chat {
        - String id
        - String lastMessage
        - LocalDateTime createdAt
        - Boolean isMine
        - User user
    }

    class ChatMessage {
        - String id
        - User sender
        - User receiver
        - String content
        - LocalDateTime createdAt
    }

    class Follow {
        - String id
        - String followedId
        - String followerId
    }

    class Notification {
        - String id
        - String targetId
        - String sourceId
        - User carriedOutBy
        - NotificationContent content
        - LocalDateTime createdAt
        - LocalDateTime updatedAt
    }

    enum NotificationContent {
        COMMENT
        UPVOTE
        PAGE_INVITATION
        DOWNVOTE
        ASSIST
        FOLLOW

        + fromString(): String
    }

    Comment --> Post : postId
    Comment --> Comment : replyTo
    Comment --> Status : status
    Comment --> User : authorId
    Comment --> User : upvoters
    Comment --> User : downvoters
    Comment --> PageProfile : pageProfile

    Post --> Category : category
    Post --> Status : status
    Post --> User : authorId
    Post --> PageProfile : pageId
    Post --> User : upvoters
    Post --> User : downvoters

    User --> Role : role
    User --> Status : status
    User --> UserProfile : userProfile

    UserProfile --> Style :  styles
    UserProfile --> Instrument :  instruments
    UserProfile --> PageProfile : following
    UserProfile --> UserProfile : following

    PageProfile --> User : members
    PageProfile --> User : owner
    PageProfile --> PageType : pageType
    PageProfile --> Status : status

    Event --> User : authorId
    Event --> PageProfile : pageId
    Event --> EventStatus : status
    Event --> UserProfile : assists
    
    Review --> UserProfile : reviewerUser
    Review --> UserProfile : reviewed
    Review --> Status : status
    Review --> UserProfile : reviewedId (if user)

    Chat "1" --> "*" ChatMessage
    Chat --> User

    ChatMessage --> User : sender
    ChatMessage --> User : receiver

    Follow --> UserProfile : follower
    Follow --> UserProfile : followed

    Notification --> User : carriedOutBy
    Notification --> NotificationContent : content
@enduml
