@startuml
actor User
boundary "UI" as UI
control "FollowService" as FS
entity "actual:UserProfile" as AUP
entity "actual:PageProfile" as APP
entity "actual:Sesion" as S
participant "UserRepository" as UR <<repository>>
participant "UserProfileRepository" as UPR <<repository>>
participant "PageProfileRepository" as PPR <<repository>>
entity "UserProfile" as UP
entity "PageProfile" as PP

User -> UI: onClickOnFollowButton()
UI -> UI: showFollowButtonState()
UI -> UI: getSesion() 
UI -> S: getSesion()
UI -> FS: toggleFollowUser()
FS -> UR: authUser()
FS -> FS: resolveType()
alt type == USER
    FS -> UPR: getById()
    UPR -> UP: getById()
    FS -> AUP: getFollowing()
    FS -> FS: isFolower()
    FS -> FS: toggleFolow()
    FS -> AUP: setFollowing()
    FS -> UPR: update()
else type == PAGE
    FS -> PPR: getById()
    PPR -> PP: getById()
    FS -> APP: getFollowing()
    FS -> FS: isFolower()
    FS -> FS: toggleFolow()
    FS -> APP: setFollowing()
    FS -> PPR: update()
end

FS -> UI: toggleFollowRes
UI -> UI: updateIsFollowing()
UI -> User: showFollowButtonState()
FS -> FS: endUS()

hide footbox
@enduml
