@startuml
title State Machine - Post
left to right direction


[*] --> Active : create()

Active --> Banned : ban()
Active --> Deleted : delete()

Banned --> Active : reactivate()
Banned --> Deleted : delete()

Deleted --> [*]

@enduml